---
app: news-website
service: news-website

frameworkVersion: '>=2.24.0'

provider:
  name: aws
  runtime: go1.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}'

functions:
  post:
    handler: bin/post
    package:
      include:
        - ./bin/post
    events:
      - http:
          path: newsitem
          method: post
          cors: true
  get:
    handler: bin/get
    package:
      include:
        - ./bin/get
    events:
      - http:
          path: news
          method: get
          cors: true

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
    SNS:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: testi
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: some-email-address
        Protocol: Email
        TopicArn: !Ref SNS
    CodeCommit:
      Type: AWS::CodeCommit::Repository
      Properties:
        RepositoryName: news-website
        Code:
          S3:
            Bucket: testi324332524523432
            Key: bla.zip
        Triggers:
          - Branches:
              - main
            DestinationArn: !Ref SNS
            Events:
              - updateReference
            Name: testi
    ManagedPolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'logs:*'
              Resource: '*'
            - Effect: Allow
              Action:
                - 'codecommit:*'
              Resource: '*'
            - Effect: Allow
              Action:
                - 'codebuild:*'
              Resource: '*'
            - Effect: Allow
              Action:
                - 's3:*'
              Resource: '*'
        ManagedPolicyName: testi
    Role:
      Type: AWS::IAM::Role
      DependsOn: ManagedPolicy
      Properties:
        AssumeRolePolicyDocument:
          {
            'Version': '2012-10-17',
            'Statement':
              [
                {
                  'Effect': 'Allow',
                  'Action': ['sts:AssumeRole'],
                  'Principal':
                    {
                      'Service':
                        [
                          'codebuild.amazonaws.com',
                          'codepipeline.amazonaws.com',
                        ],
                    },
                },
              ],
          }
        ManagedPolicyArns:
          - !Ref ManagedPolicy
        RoleName: testi
    CodeBuild:
      Type: AWS::CodeBuild::Project
      DependsOn: Role
      Properties:
        Artifacts:
          Type: no_artifacts
        Environment:
          Type: LINUX_CONTAINER
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/standard:4.0
        Name: testi
        ServiceRole: testi
        Source:
          Location: https://git-codecommit.eu-central-1.amazonaws.com/v1/repos/news-website
          Type: CODECOMMIT
        SourceVersion: refs/heads/main
    CodePipeline:
      Type: AWS::CodePipeline::Pipeline
      Properties:
        RoleArn: !GetAtt Role.Arn
        Stages:
          - Name: Source
            Actions:
              - Name: Source
                ActionTypeId:
                  Category: Source
                  Owner: AWS
                  Version: 1
                  Provider: CodeCommit
                OutputArtifacts:
                  - Name: CODE_ZIP
                Configuration:
                  RepositoryName: news-website
                  BranchName: main
                  PollForSourceChanges: 'false'
          - Name: Build
            Actions:
              - Name: Build
                InputArtifacts:
                  - Name: CODE_ZIP
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Version: 1
                  Provider: CodeBuild
                Configuration:
                  ProjectName: testi
        ArtifactStore:
          Type: S3
          Location: testi324332524523432
  Outputs:
    SNS:
      Value:
        Ref: SNS
    SNSSubscription:
      Value:
        Ref: SNSSubscription
    CodeCommit:
      Value:
        Ref: CodeCommit
    ManagedPolicy:
      Value:
        Ref: ManagedPolicy
    Role:
      Value:
        Ref: Role
    CodeBuild:
      Value:
        Ref: CodeBuild
